# Populate this after `terraform apply` using the `instance_public_ip` output,
[webservers]
dbs-devops-server ansible_host=REPLACE_WITH_VM_PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
